services:
  backend:
    build:
      context: backend
      dockerfile: Dockerfile
      args:
        GO_ENV: ${GO_ENV}
        CGO_ENABLED: ${CGO_ENABLED}
    volumes:
      - ./backend:/app
    ports:
      - "8080:8080"
    environment:
      GO_ENV: ${GO_ENV}
      CGO_ENABLED: ${CGO_ENABLED}
    command: ["make", "dev"]

  frontend:
    build:
      context: frontend
      dockerfile: Dockerfile
      args:
        NODE_ENV: ${NODE_ENV}
    volumes:
      - node_modules:/app/node_modules
      - ./frontend:/app
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: ${NODE_ENV}
      VITE_API_URL: "http://backend:8080"
    command: ["npm", "run", "dev"]

volumes:
  node_modules:
